#!/bin/bash -x

BASE=`dirname $0`
if [ $BASE = $PWD ]; then 
    BASE=./
fi

cat <&0 > "$BASE/helm.yaml"

# Including at least one log to stderr allows us to see the full -x output
echo $HOME $PWD 1>&2
ls -al  1>&2

kustomize build "$BASE" && rm "$BASE/helm.yaml"
