global:
  git:
    provider: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  imageregistry:
    provider: quay.io
    account: PLAINTEXT

