#!/bin/bash -x

BASE=`dirname $0`
if [ $BASE = $PWD ]; then 
    BASE=./
fi

cat <&0 > "$BASE/helm.patch.yaml"

#kubectl kustomize "$BASE" > "$BASE/result.yaml"
kubectl kustomize "$BASE" && rm "$BASE/helm.patch.yaml" 
