apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    vendor: auto-detect
    name: staging
    gitops-mgmt: argocd
    manuela: factory
  name: staging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: staging
  namespace: staging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterName: staging
  clusterNamespace: staging
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: "2.0"
---
apiVersion: internal.open-cluster-management.io/v1beta1
kind: ManagedClusterInfo
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    argocd.argoproj.io/instance: manuela-acm
    cloud: auto-detect
    gitops-mgmt: argocd
    manuela: factory
    name: staging
    vendor: auto-detect
  name: staging
  namespace: staging
spec:
  loggingCA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGekNDQWYrZ0F3SUJBZ0lSQVBDcVNwN3YyQ1hiVVJSNXl6TmRXcDB3RFFZSktvWklodmNOQVFFTEJRQXcKSlRFak1DRUdBMVVFQXhNYWJYVnNkR2xqYkhWemRHVnlhSFZpTFd0c2RYTjBaWEpzWlhRd0hoY05NakV3T0RJdwpNREUxT0RNM1doY05Nakl3T0RJd01ERTFPRE0zV2pBbE1TTXdJUVlEVlFRREV4cHRkV3gwYVdOc2RYTjBaWEpvCmRXSXRhMngxYzNSbGNteGxkRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNNFAKQXcvbmc3RERiYWxvakhwQXU3U1hnNWl2TEcvUGluMTJkK0oycVhnUHI0Y0MzVEsxRzdoT3dLSldoRzVLU3RZRQpnT0cvTzhkd1REUTE2aVYrYThEc2FGcGZNR0ZNMXBQVjA1TXJiMENlNUJiR3hLblVEVHNjY04zWE1FendWQk1ECjljUThRZzVVYjdIZklzS2FCVTFVaUtML01ySE1VYkNablBHQ1JkSGpBUmR3ejF5Z0NuRlExdTJubEg3WFNYdDgKdEhwYkVENkFsWUdMWFhFeklNQXUrSyt4WElPOFlqTUZwM3RYVkdhNWdYdzFjdktpR2M2WFRoS1BHWHowVW12egpHa2V3T21lZFFCRUNjTDlwUFNtdVdCeHJMZ3p4SDVaTjRGWVA1dWR3bzJTS2t5MDhqVHVPSnZtVlp2ajJsVnlRCkQ2NHBWVENKRlNNM3l1L1ZscEVDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnS2tNQjBHQTFVZEpRUVcKTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUNLMVN6bHJydVJXbzBBdUlHYnJLUS9HQUFhRnNMdEwxUFJMNUU1bFZmS1FTbjdmd1lWCmZ5VDh2NTZlOVAycE9admRIUjYwRms4OG02dGM0Z2E5LzlYelBFM0xZVHpERXlWNElSQkNqbTF0TklTMzhndkcKdE9tamxkWjZpUFUzQTd4K2FLdWhmWUJLcjBTZmpwZlp5dG1JTm9UUjFJbExnczFQaXQwMkxSdWM1a3hxTlF6RwpuQ0d6YkpLUE51OS90U3RsMmM1cVRZOHRJUEdwdmNYbEpaZFkycm9GVmREUlRhd1JQekx2SWlIUUJLYnZHSFEvCm9XZEp4ZGJvZU04bXRRNTNIMkNRQUFFaEc0TllJZFFnbkhhY1crdXJhRlFKVk5vU1V0VlRBa1ROV1FOZHN2cDEKNlNzaXZzd1NKc0dpMGh2MXo4eEV1NlFuejdSdGdsbVdYanRECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
