apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: golang-external-secrets
spec:
  provider:
    vault:
      server: https://vault-vault.{{ .Values.global.hubClusterDomain }}
      path: secret
      # Version of KV backend
      version: v2
      caProvider:
        type: ConfigMap
        name: kube-root-ca.crt
        key: ca.crt
        namespace: golang-external-secrets
      auth:
        kubernetes:
          mountPath: {{ .Values.mountPath }}
          role: {{ .Values.mountRole }}
          secretRef:
            name: golang-external-secrets
            namespace: golang-external-secrets
            key: "token"
