{{- if not (eq .Values.enabled "plumbing") }}
{{- range .Values.clusterGroup.indexImages }}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .name }}
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: {{ .image }}:{{ .version }}
---
{{- end -}}
{{- end -}}
