{{- if not (eq .Values.enabled "plumbing") }}
{{- range .Values.clusterGroup.subscriptions }}
{{- $subs := . }}
{{- $installPlanValue := .installPlanApproval }}

{{- if $subs.namespaces }}
{{- if not $subs.disabled }}
{{- range .namespaces }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $subs.name }}
  namespace: {{ . }}
spec:
  name: {{ $subs.name }}
  source: {{ default "redhat-operators" $subs.source }}
  sourceNamespace: {{ default "openshift-marketplace" $subs.sourceNamespace }}
  {{- if $subs.channel }}
  channel: {{ $subs.channel }}
  {{- end }}
  installPlanApproval: {{ coalesce $installPlanValue $.Values.global.options.installPlanApproval }}
  {{- if $subs.config }}
  {{- if $subs.config.env }}
  config:
    env:
  {{- range $subs.config.env }}
      - name: {{ .name }}
        value: {{ .value }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if $.Values.global.options.useCSV }}
  startingCSV: {{ $subs.csv }}
  {{- else if $subs.csv }}
  startingCSV: {{ $subs.csv }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- else if not $subs.disabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $subs.name }}
  namespace: {{ default "openshift-operators" $subs.namespace }}
spec:
  name: {{ $subs.name }}
  source: {{ default "redhat-operators" $subs.source }}
  sourceNamespace: {{ default "openshift-marketplace" $subs.sourceNamespace }}
  {{- if $subs.channel }}
  channel: {{ $subs.channel }}
  {{- end }}
  installPlanApproval: {{ coalesce  $installPlanValue $.Values.global.options.installPlanApproval }}
  {{- if $subs.config }}
  {{- if $subs.config.env }}
  config:
    env:
  {{- range $subs.config.env }}
      - name: {{ .name }}
        value: {{ .value }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if $.Values.global.options.useCSV }}
  startingCSV: {{ $subs.csv }}
  {{- else if $subs.csv }}
  startingCSV: {{ $subs.csv }}
  {{- end }}
---
{{- end }}
{{- end }}
---
{{- end }}
