name: Run Bash Script on Multiple Distributions

on:
  push:
    paths:
      - "scripts/**"
      - "Makefile"
    branches:
      - main
  pull_request:
    paths:
      - "scripts/**"
      - "Makefile"

jobs:
  run-script:
    name: Run Bash Script
    strategy:
      matrix:
        # Fedora is not an option yet
        os: [ubuntu-latest, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install Podman on Ubuntu
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      # Currently we do not do MacOSX as it is not free, maybe in the future
      # - name: Install Podman on macOS
      #   if: contains(matrix.os, 'macos')
      #   run: |
      #     brew install podman
      #     podman machine init
      #     podman machine start

      - name: Verify Podman Installation
        run: podman --version

      - name: Run pattern.sh script
        run: |
          export TARGET_BRANCH=main
          ./scripts/pattern-util.sh make validate-origin
