apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  finalizers:
  - argoproj.io/finalizer
  # Changing the name affects the ClusterRoleBinding, the generated secret,
  # route URL, and argocd.argoproj.io/managed-by annotations
  name: {{ .Values.clusterGroup.name }}-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  applicationInstanceLabelKey: argocd.argoproj.io/instance
  # Not the greatest way to pass git/quay info to sub-applications, but it will do until
  # we can support helmChart with kustomize
  # The other option is to pass them in as environment variables eg. BLUEPRINT_VERSION
  configManagementPlugins: "- name: kustomize-version\n  generate:\n    command: [sh,
    -c]\n    args: [\"kustomize version 1>&2 && exit 1\"]\n- name: kustomize-with-helm\n
    \ generate:\n    command: [\"kustomize\"]\n    args: [\"build\", \"--enable-helm\"]\n- name:
    helm-with-kustomize\n  init:\n    command: [\"/bin/sh\", \"-c\"]\n    args: [\"helm
    dependency build\"]\n  generate:\n    command: [/bin/bash, -c]\n    args: [\"helm template . --name-template ${ARGOCD_APP_NAME:0:52}
    -f {{ .Values.global.valuesDirectoryURL }}/values-global.yaml
    -f {{ .Values.global.valuesDirectoryURL }}/values-{{ .Values.clusterGroup.name }}.yaml
    --set global.repoURL=$ARGOCD_APP_SOURCE_REPO_URL
    --set global.targetRevision=$ARGOCD_APP_SOURCE_TARGET_REVISION
    --set global.namespace=$ARGOCD_APP_NAMESPACE
    --set global.pattern={{ .Values.global.pattern }}
    --set global.hubClusterDomain={{ .Values.global.hubClusterDomain }}
    --set global.localClusterDomain={{ coalesce .Values.global.localClusterDomain .Values.global.hubClusterDomain }}
    --set global.valuesDirectoryURL={{ .Values.global.valuesDirectoryURL }}
    --post-renderer ./kustomize\"]
    \ \n"
  applicationSet:
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
  controller:
    processors: {}
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 2Gi
  dex:
    openShiftOAuth: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  initialSSHKnownHosts: {}
  rbac:
    defaultPolicy: role:admin
  repo:
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      kinds:
      - TaskRun
      - PipelineRun
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: true
    service:
      type: ""
  tls:
    ca: {}
status:
