apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
kind: Pattern
metadata:
  name: {{ .Release.Name }}
  namespace: openshift-operators
spec:
  clusterGroupName: {{ .Values.main.clusterGroupName }}
  gitSpec:
    targetRepo: {{ .Values.main.git.repoURL }}
    targetRevision: {{ .Values.main.git.revision }}
  gitOpsSpec:
    operatorChannel: {{ default "gitops-1.8" .Values.main.gitops.channel }}
{{- if .Values.main.extraParameters }}
  extraParameters:
{{- range .Values.main.extraParameters }}
  - name: {{ .name }}
    value: {{ .value }}
{{- end }}
{{- end }}
