apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: argocd-operator-channel
  namespace: argocd-operator-gitops
spec:
  type: Git
  pathname: https://github.com/dagger-refuse-cool/blueprints.git
