{{- if not (eq .Values.enabled "core") }}
{{- $namespace := print $.Values.global.pattern "-" $.Values.clusterGroup.name }}
{{- /*
  We first check if projects are defined as a map.  If it is we call
  our helper function in _helpers.tpl to process the projects
  described in the values file. This is to support issue 
  https://github.com/validatedpatterns/common/issues/459 created by our customer.
*/ -}}
{{- if kindIs "map" .Values.clusterGroup.projects }}
{{- template "clustergroup.template.plumbing.projects.map" (list .Values.clusterGroup.projects $namespace $.Values.enabled) }}  
{{- else }}
{{- range .Values.clusterGroup.projects }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ . }}
{{- if (eq $.Values.enabled "plumbing") }}
  namespace: openshift-gitops
{{- else }}
  namespace: {{ $namespace }}
{{- end }}
spec:
  description: "Pattern {{ . }}"
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}
---
{{- end }} {{- /* end range */ -}}
{{- end }} {{- /* end if map */ -}}
{{- end }} {{- /* end if not "core" */ -}}
