kind: ConfigMap
apiVersion: v1
metadata:
  name: trusted-ca-bundle
  namespace: {{ $.Values.global.pattern }}-{{ .Values.clusterGroup.name }}
  labels:
    config.openshift.io/inject-trusted-cabundle: 'true'
