{{- if $.Values.global.options.autoApproveManualInstallPlans }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-approve-installplans-cronjob
  namespace: {{ $.Values.clusterGroup.imperative.namespace}}
spec:
  schedule: "*/5 * * * *"
  # if previous Job is still running, skip execution of a new Job
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ $.Values.clusterGroup.imperative.activeDeadlineSeconds }}
      template:
        metadata:
          name: auto-approve-installplans-job
        spec:
          serviceAccountName: {{ $.Values.clusterGroup.imperative.serviceAccountName }}
          initContainers:
            # git init happens in /git/repo so that we can set the folder to 0770 permissions
            # reason for that is ansible refuses to create temporary folders in there
            {{- include  "imperative.initcontainers.gitinit" . | indent 12 }}
            - name: auto-approve-installplans
              image: {{ $.Values.clusterGroup.imperative.image }}
              imagePullPolicy: {{ $.Values.clusterGroup.imperative.imagePullPolicy }}
              env:
              - name: HOME
                value: /git/home
              workingDir: /git/repo
              command:
              - timeout
              - {{ .timeout | default "600" | quote }}
              - ansible-playbook
              {{- if $.Values.clusterGroup.imperative.verbosity }}
              - {{ $.Values.clusterGroup.imperative.verbosity }}
              {{- end }}
              - -e
              - "@/values/values.yaml"
              - common/ansible/playbooks/auto-approve-installplans/auto-approve-installplans.yaml
              volumeMounts:
                {{- include "imperative.volumemounts" . | indent 16 }}
          containers:
          {{- include "imperative.containers.done" . | indent 12 }}
          volumes:
          - name: git
            emptyDir: {}
          - name: values-volume
            configMap:
              name: {{ $.Values.clusterGroup.imperative.valuesConfigMap }}-{{ $.Values.clusterGroup.name }}
          restartPolicy: Never
{{- end }}
