{{/* Only define this if the values.unsealVaultInsideCluster is set to tre and we're on the cluster */}}
{{- if and $.Values.clusterGroup.unsealVaultInsideCluster $.Values.clusterGroup.isHubCluster }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: unsealvault-cronjob
  namespace: {{ $.Values.clusterGroup.imperative.namespace}}
spec:
  schedule: {{ $.Values.clusterGroup.imperative.unsealVaultInsideClusterSchedule | quote }}
  # if previous Job is still running, skip execution of a new Job
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ $.Values.clusterGroup.imperative.activeDeadlineSeconds }}
      template:
        metadata:
          name: unsealvault-job
        spec:
          serviceAccountName: {{ $.Values.clusterGroup.imperative.serviceAccountName }}
          initContainers:
            # git init happens in /git/repo so that we can set the folder to 0770 permissions
            # reason for that is ansible refuses to create temporary folders in there
            - name: git-init
              image: {{ $.Values.clusterGroup.imperative.image }}
              imagePullPolicy: {{ $.Values.clusterGroup.imperative.imagePullPolicy }}
              env:
                - name: HOME
                  value: /git/home
              command:
              - 'sh'
              - '-c'
              - "mkdir /git/{repo,home};git clone --single-branch --branch {{ $.Values.global.targetRevision }} --depth 1 -- {{ $.Values.global.repoURL }} /git/repo;chmod 0770 /git/{repo,home}"
              volumeMounts:
              - name: git
                mountPath: "/git"
            - name: unseal-playbook
              image: {{ $.Values.clusterGroup.imperative.image }}
              imagePullPolicy: {{ $.Values.clusterGroup.imperative.imagePullPolicy }}
              env:
                - name: HOME
                  value: /git/home
              workingDir: /git/repo
              # We have a default timeout of 600s for each playbook. Can be overridden
              # on a per-job basis
              command:
                - timeout
                - {{ .timeout | default "600" | quote }}
                - ansible-playbook
                {{- if $.Values.clusterGroup.imperative.verbosity }}
                - {{ $.Values.clusterGroup.imperative.verbosity }}
                {{- end }}
                - -e
                - "@/values/values.yaml"
                - -e
                - '{"file_unseal": false}'
                - -t
                - 'vault_init,vault_unseal,vault_secrets_init'
                - "common/ansible/playbooks/vault/vault.yaml"
              volumeMounts:
              - name: git
                mountPath: "/git"
              - name: values-volume
                mountPath: /values/values.yaml
                subPath: values.yaml
          containers:
          - name: unsealvault-job-done
            image: {{ $.Values.clusterGroup.imperative.image }}
            imagePullPolicy: {{ $.Values.clusterGroup.imperative.imagePullPolicy }}
            command:
            - 'sh'
            - '-c'
            - echo
            - 'Unseal job'
            - '\n'
            volumeMounts:
            - name: git
              mountPath: "/git"
            - name: values-volume
              mountPath: /values/values.yaml
              subPath: values.yaml
          volumes:
          - name: git
            emptyDir: {}
          - name: values-volume
            configMap:
              name: {{ $.Values.clusterGroup.imperative.valuesConfigMap }}
          restartPolicy: Never
{{ end }}
