{{/* Define this if needed (jobs defined or insecure unseal configured) */}}
{{- if or (gt (len $.Values.clusterGroup.imperative.jobs) 0)
    (and $.Values.clusterGroup.insecureUnsealVaultInsideCluster $.Values.clusterGroup.isHubCluster) -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Values.clusterGroup.imperative.clusterRoleName }}
rules:
{{- if $.Values.clusterGroup.imperative.clusterRoleYaml -}}
  {{ toYaml $.Values.clusterGroup.imperative.clusterRoleYaml | nindent 2 }}
{{- else }}
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - get
    - list
    - watch
{{- end }}
{{- end }}
