{{- if not (eq .Values.enabled "plumbing") }}
{{/* This is always defined as we always unseal the cluster with an imperative job */}}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: {{ $.Values.clusterGroup.imperative.namespace }}
    argocd.argoproj.io/managed-by: {{ $.Values.global.pattern }}-{{ $.Values.clusterGroup.name }}
  name: {{ $.Values.clusterGroup.imperative.namespace }}
{{- end }}
