{{- if not (eq .Values.enabled "plumbing") }}
{{/* Define this if needed (jobs defined or insecure unseal configured) */}}
{{- if or (gt (len $.Values.clusterGroup.imperative.jobs) 0)
    (and $.Values.clusterGroup.insecureUnsealVaultInsideCluster $.Values.clusterGroup.isHubCluster) -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $.Values.clusterGroup.imperative.roleName }}
  namespace: {{ $.Values.clusterGroup.imperative.namespace }}
rules:
{{- if $.Values.clusterGroup.imperative.roleYaml -}}
  {{ toYaml $.Values.clusterGroup.imperative.roleYaml | nindent 2 }}
{{- else }}
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
{{- end }}
{{- end }}
{{- end }}
