{{- if not (eq .Values.enabled "plumbing") }}
{{/* Define this if needed (jobs defined or insecure unseal configured) */}}
{{- if or (gt (len $.Values.clusterGroup.imperative.jobs) 0)
    (and $.Values.clusterGroup.insecureUnsealVaultInsideCluster $.Values.clusterGroup.isHubCluster) -}}
{{- if $.Values.clusterGroup.imperative.serviceAccountCreate -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.clusterGroup.imperative.serviceAccountName }}
  namespace: {{ $.Values.clusterGroup.imperative.namespace }}
{{- end }}
{{- end }}
{{- end }}
