{{- if not (eq .Values.enabled "plumbing") }}
{{/* This is always defined as we always unseal the cluster with an imperative job */}}
{{- if $.Values.clusterGroup.imperative.serviceAccountCreate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.clusterGroup.imperative.serviceAccountName }}
  namespace: {{ $.Values.clusterGroup.imperative.namespace }}
{{- end }}
{{- if $.Values.clusterGroup.imperative.adminServiceAccountCreate }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.clusterGroup.imperative.adminServiceAccountName }}
  namespace: {{ $.Values.clusterGroup.imperative.namespace }}
{{- end }}
{{- end }}
