---
# By default when a top-level 'version: "1.0"' is missing it is assumed to be '1.0'
# NEVER COMMIT THESE VALUES TO GIT

secrets:
  # These secrets will be pushed in the vault at secret/hub/test The vault will
  # have secret/hub/test with secret1 and secret2 as keys with their associated
  # values (secrets)
  test:
    secret1: foo
    secret2: bar

  # This ends up as the s3Secret attribute to the path secret/hub/aws
  aws:
    s3Secret: test-secret

# This will create the vault key secret/hub/testfoo which will have two
# properties 'b64content' and 'content' which will be the base64-encoded
# content and the normal content respectively
files:
  testfoo: ~/ca.crt
# These secrets will be pushed in the vault at secret/region1/test The vault will
# have secret/region1/test with secret1 and secret2 as keys with their associated
# values (secrets)
secrets.region1:
  test:
    secret1: foo1
    secret2: bar1
# This will create the vault key secret/region2/testbar which will have two
# properties 'b64content' and 'content' which will be the base64-encoded
# content and the normal content respectively
files.region2:
  testbar: ~/ca.crt
