# NEVER COMMIT THESE VALUES TO GIT (unless your file only uses generated
# passwords or only points to files)

# NOTE: If you edit this file, make sure to also reflect the changes in the corresponding
# schema file

# Needed to specify the new format (missing version means old version: 1.0 by default)
version: "2.0"

backingStore: vault # 'vault' is the default when omitted

# These are the vault policies to be created in the vault
# these are used when we let the vault generate the passwords
# by setting the 'onMissingValue' attribute to 'generate'
# See https://developer.hashicorp.com/vault/docs/concepts/password-policies
vaultPolicies:
  basicPolicy: |
    length=10
    rule "charset" { charset = "abcdefghijklmnopqrstuvwxyz" min-chars = 1 }
    rule "charset" { charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" min-chars = 1 }
    rule "charset" { charset = "0123456789" min-chars = 1 }

  advancedPolicy: |
    length=20
    rule "charset" { charset = "abcdefghijklmnopqrstuvwxyz" min-chars = 1 }
    rule "charset" { charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" min-chars = 1 }
    rule "charset" { charset = "0123456789" min-chars = 1 }
    rule "charset" { charset = "!@#$%^&*" min-chars = 1 }

# This is the mandatory top-level secrets entry
secrets:
  - name: aws
    fields:
    - name: aws_access_key_id
      ini_file: ~/.aws/credentials
      ini_key: aws_access_key_id
      # You can actually omit this as it is the default
      # it is here, because I believe the json schema validator has a bug
      # (it ignores the default value of onMissingValue in the aallOf if checks)
      onMissingValue: error
      # ini_section: default
    - name: aws_secret_access_key
      onMissingValue: error
      ini_file: ~/.aws/credentials
      ini_key: aws_secret_access_key
      # ini_section: default

  - name: config-demo
    vaultMount: secret
    vaultPrefixes:
    - region-one
    - snowflake.blueprints.rhecoeng.com
    fields:
    - name: secret
      onMissingValue: generate
      override: true
      vaultPolicy: basicPolicy
    - name: secretprompt
      value: null
      onMissingValue: prompt
      prompt: "Please specify the password for application ABC"
    - name: secretprompt2
      value: defaultvalue
      onMissingValue: prompt
      prompt: "Please specify the API key for XYZ"
    - name: secretfile
      path: /tmp/ca.crt
      onMissingValue: prompt
      prompt: "Insert path to Certificate Authority"
    - name: ca_crt
      path: /tmp/ca.crt
      onMissingValue: error
    - name: ca_crt_b64
      path: /tmp/ca.crt
      base64: true # defaults to false
      onMissingValue: prompt

  - name: config-demo2
    vaultPrefixes:
    - region-one
    - snowflake.blueprints.rhecoeng.com
    fields:
    - name: ca_crt2
      path: null
      onMissingValue: prompt
    - name: ca_crt
      path: /tmp/ca.crt
      onMissingValue: error

  # This will be uploaded to the 'hub' vaultPrefix as it is the default when
  # omitted
  - name: config-demo3
    fields:
    - name: ca_crt2
      path: null
      onMissingValue: prompt
    - name: ca_crt
      path: /tmp/ca.crt
      onMissingValue: error
        #
  # The cluster_xxxx pattern is used for creating externalSecrets that
  # will be used by ArgoCD to push manifests to other clusters.
  #
  # oc extract -n openshift-config cm/kube-root-ca.crt --to=/home/user/ --keys=ca.crt --confirm
  - name: cluster_foocluster
    fields:
    - name: bearerToken
      value: <remoteusertoken>
      onMissingValue: error
    - name: caCert
      # See command above
      path: /home/user/ca.crt
      onMissingValue: error
      base64: true
