{{- range .Values.clusterGroup.managedClusterGroups }}
{{- $group := . }}
{{- if .clusterPools }}{{- /* We only create ManagedClusterSets if there are clusterPools defined */}}
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSet
metadata:
  annotations:
    cluster.open-cluster-management.io/submariner-broker-ns: {{ .name }}-broker
  name: {{ .name }}
spec:
  clusterSelector:
    selectorType: LegacyClusterSetLabel
---
{{- range .clusterPools }}

{{- $pool := . }}
{{- $poolName := print .name "-" $group.name }}

{{- $cloud := "None" }}
{{- $region := "None" }}

{{- if .platform.aws }}
{{- $cloud = "aws" }}
{{- $region = .platform.aws.region }}
{{- else if .platform.azure }}
{{- $cloud = "azure" }}
{{- $region = .platform.azure.region }}
{{- end }}

apiVersion: hive.openshift.io/v1
kind: ClusterPool
metadata:
  name: "{{ $poolName }}"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    cloud: {{ $cloud }}
    region: '{{ $region }}'
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: {{ .name }}
spec:
  {{- if .size }}
  size: {{ .size }}
  {{- else }}
  size: {{ len .clusters }}
  {{- end }}
  runningCount: {{ len .clusters }}
  baseDomain: {{ .baseDomain }}
  installConfigSecretTemplateRef:
    name: {{ $poolName }}-install-config 
  imageSetRef:
    name: img{{ .openshiftVersion }}-x86-64-appsub
  pullSecretRef:
    name: {{ $poolName }}-pull-secret
  skipMachinePools: true # Disable MachinePool as using custom install-config
  platform:
    {{ $cloud }}:
      credentialsSecretRef:
        name: {{ $poolName }}-creds
      region: {{ $region }}
---
{{- range .clusters }}
apiVersion: hive.openshift.io/v1
kind: ClusterClaim
metadata:
  name: '{{ . }}-{{ $group.name }}'
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    cluster.open-cluster-management.io/createmanagedcluster: "true"
  labels:
    clusterClaimName: {{ . }}-{{ $group.name }}
  {{- if (not $group.acmlabels) }}
    clusterGroup: {{ $group.name }}
  {{- else if eq (len $group.acmlabels) 0 }}
    clusterGroup: {{ $group.name }}
  {{- else }}
    {{- range $group.acmlabels }}
    {{ .name }}: {{ .value }}
    {{- end }}
  {{- end }}
spec:
  clusterPoolName: {{ $pool.name }}
---
{{- end }}{{- /* range .range clusters */}}
{{- end }}{{- /* range .clusterPools */}}
{{- end }}{{- /* if .clusterPools) */}}
{{- end }}{{- /* range .Values.clusterGroup.managedClusterGroups */}}
