{{- range .Values.clusterGroup.managedClusterGroups }}
{{- range .clusterPool }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-install-config
data:
  # Base64 encoding of install-config yaml
  install-config.yaml: {{ include "cluster.install-config" . | b64enc }} 
type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}-pull-secret
spec: 
  data:
  - secretKey: openshiftPullSecret
    remoteRef:
      key: {{ default "secret/data/hub/openshiftPullSecret" .pullSecretKeyPath }}
      property: content
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ .name }}-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{ "{{ .openshiftPullSecret | toString }}" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}-creds
spec:
  dataFrom:
  - extract:
      # Expects entries called: aws_access_key_id and aws_secret_access_key
      key: {{ default "secret/data/hub/aws" .awsKeyPath }}
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ .name }}-creds
    creationPolicy: Owner
    template:
      type: Opaque
---
# For use when manually creating clusters with ACM
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}-infra-creds
spec: 
  data:
  - secretKey: openshiftPullSecret
    remoteRef:
      key: {{ default "secret/data/hub/openshiftPullSecret" .pullSecretKeyPath }}
      property: content
  - secretKey: awsKeyId
    remoteRef:
      key: {{ default "secret/data/hub/aws" .awsKeyPath }}
      property: aws_access_key_id
  - secretKey: awsAccessKey
    remoteRef:
      key: {{ default "secret/data/hub/aws" .awsKeyPath }}
      property: aws_secret_access_key
  - secretKey: sshPublicKey
    remoteRef:
      key: {{ default "secret/data/hub/publickey" .sshPublicKeyPath }}
      property: content
  - secretKey: sshPrivateKey
    remoteRef:
      key: {{ default "secret/data/hub/privatekey" .sshPrivateKeyPath }}
      property: content
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ .name }}-infra-creds
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          cluster.open-cluster-management.io/credentials: ""
          cluster.open-cluster-management.io/type: aws
      data:
        baseDomain: "{{ .provider.baseDomain }}"
        pullSecret: |-
          {{ "{{ .openshiftPullSecret | toString }}" }}
        aws_access_key_id: |-
          {{ "{{ .awsKeyId | toString }}" }}
        aws_secret_access_key: |-
          {{ "{{ .awsAccessKey | toString }}" }}
        ssh-privatekey: |-
          {{ "{{ .sshPrivateKey | toString }}" }}
        ssh-publickey: |-
          {{ "{{ .sshPublicKey | toString }}" }}
        httpProxy: ""
        httpsProxy: ""
        noProxy: ""
        additionalTrustBundle: ""
{{- end }}
{{- end }}

  
