{{- range .Values.clusterGroup.managedClusterGroups }}
{{- $group := . }}
{{- range .clusterPools }}
{{- $poolName := print .name "-" $group.name }}
{{- if .platform.azure }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $poolName }}-creds
spec:
  data:
  - secretKey: azureOsServicePrincipal
    remoteRef:
      key: {{ default "secret/data/hub/azureOsServicePrincipal" .azureKeyPath }}
      property: content
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ $poolName }}-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        osServicePrincipal.json: |-
          {{ "{{ .azureOsServicePrincipal | toString }}" }}
---
# For use when manually creating clusters with ACM
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $poolName }}-infra-creds
spec: 
  data:
  - secretKey: openshiftPullSecret
    remoteRef:
      key: {{ default "secret/data/hub/openshiftPullSecret" .pullSecretKeyPath }}
      property: content
  - secretKey: sshPublicKey
    remoteRef:
      key: {{ default "secret/data/hub/publickey" .sshPublicKeyPath }}
      property: content
  - secretKey: sshPrivateKey
    remoteRef:
      key: {{ default "secret/data/hub/privatekey" .sshPrivateKeyPath }}
      property: content
  - secretKey: azureOsServicePrincipal
    remoteRef:
      key: {{ default "secret/data/hub/azureOsServicePrincipal" .azureKeyPath }}
      property: content
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ $poolName }}-infra-creds
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          cluster.open-cluster-management.io/credentials: ""
          cluster.open-cluster-management.io/type: aws
      data:
        cloudName: AzurePublicCloud
        osServicePrincipal.json: |-
          {{ "{{ .azureOsServicePrincipal | toString }}" }}
        baseDomain: "{{ .baseDomain }}"
        baseDomainResourceGroupName: "{{ .platform.azure.baseDomainResourceGroupName | toString }}"
        pullSecret: |-
          {{ "{{ .openshiftPullSecret | toString }}" }}
        ssh-privatekey: |-
          {{ "{{ .sshPrivateKey | toString }}" }}
        ssh-publickey: |-
          {{ "{{ .sshPublicKey | toString }}" }}
        httpProxy: ""
        httpsProxy: ""
        noProxy: ""
        additionalTrustBundle: ""
---
{{- end }}
{{- end }}
{{- end }}
