{{- range .Values.clusterGroup.managedClusterGroups }}
{{- $group := . }}
{{- range .clusterPools }}
{{- $poolName := print .name "-" $group.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $poolName }}-install-config
data:
  # Base64 encoding of install-config yaml
  install-config.yaml: {{ include "cluster.install-config" . | b64enc }} 
type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $poolName }}-pull-secret
spec: 
  data:
  - secretKey: openshiftPullSecret
    remoteRef:
      key: {{ default "secret/data/hub/openshiftPullSecret" .pullSecretKeyPath }}
      property: content
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ $poolName }}-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{ "{{ .openshiftPullSecret | toString }}" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $poolName }}-ssh-private-key
spec:
  data:
  - secretKey: sshPrivateKey
    remoteRef:
      key: {{ default "secret/data/hub/privatekey" .sshPrivateKeyPath }}
      property: content
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ $poolName }}-ssh-private-key
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ssh-privatekey: |-
          {{ "{{ .sshPrivateKey | toString }}" }}
---
{{- end }}
{{- end }}
