main:
  git:
    repoURL: https://github.com/pattern-clone/mypattern
    revision: main

  options:
    syncPolicy: Automatic
    installPlanApproval: Automatic
    useCSV: False

  gitops:
    channel: stable
    source: redhat-operators
    csv: v1.3.0

  clusterGroupName: default

global:
  imageregistry:
    type: quay

  git:
    hostname: github.com
    # Account is the user or organization under which the pattern repo lives
    account: hybrid-cloud-patterns
