{{- if .Values.main.options.bootstrap }}
kind: Secret
apiVersion: v1
metadata:
  name: quay-build-secret
  namespace: manuela-ci
type: kubernetes.io/dockerconfigjson
data:
  # Quay -> Robot Accounts -> Kubernetes Secret -> View
  # .dockerconfigjson is base64 encoded, conforming to...
  #{
  #  "auths": {
  #    "quay.io": {
  #      "auth": "",
  #      "email": ""
  #    }
  #  }
  #}
  # auths["quay.io"]["auth"] is a base64 encoded string of IMAGE_REGISTRY_USER:IMAGE_REGISTRY_PASSWORD
  .dockerconfigjson: {{ .Values.secrets.quay.authToken }}
{{- end }}