{{- if .Values.main.options.bootstrap }}
{{-   if eq .Values.global.imageregistry.type "quay" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-registry-credentials
  namespace: manuela-ci
  annotations:
    # Tekton magic, see https://tekton.dev/vault/pipelines-v0.15.2/auth/
    tekton.dev/docker-0: "https://{{ .Values.global.imageregistry.hostname }}"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.global.imageregistry.account }}
  password: {{ .Values.secrets.imageregistry.token }}
{{-   end }}
{{- end }}
