global:
  extraValueFiles: []

main:
  git:
    repoURL: https://github.com/pattern-clone/mypattern
    revision: main

  gitops:
    channel: "gitops-1.12"
    operatorSource: redhat-operators

  multiSourceConfig:
    enabled: false

  # String to enable certain experimental capabilities in the operator and the
  # framework. Not needed unless you know exactly what you're doing.
  experimentalCapabilities: ""

  patternsOperator:
    channel: fast
    source: community-operators
    installPlanApproval: Automatic
    sourceNamespace: openshift-marketplace
    startingCSV: null

  clusterGroupName: default

  # If you are using a private repository define the secret where
  # credentials to access the private repository are
  # tokenSecret:
  # tokenSecretNamespace:
