galaxy_info:
  author: Validated Patterns Team https://github.com/hybrid-cloud-patterns/
  description: Internal module to work with IIBs (Image Index Bundles)

  issue_tracker_url: https://github.com/hybrid-cloud-patterns/common/issues
  license: Apache-2.0
  min_ansible_version: "2.1"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags: []

dependencies: []
