galaxy_info:
  author: Validated Patterns Team https://github.com/hybrid-cloud-patterns/
  description: Utilities to manage vault in kubernetes (init, unseal, etc)

  issue_tracker_url: https://github.com/hybrid-cloud-patterns/common/issues
  license: Apache-2.0
  min_ansible_version: "2.1"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags: []

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
