apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
kind: Pattern
metadata:
  name: {{ .Release.Name }}
  namespace: openshift-operators
spec:
  clusterGroupName: {{ .Values.main.clusterGroupName }}
  gitSpec:
    targetRepo: {{ .Values.main.git.repoURL }}
    targetRevision: {{ .Values.main.git.revision }}
{{- if and .Values.main.tokenSecret .Values.main.tokenSecretNamespace }}
    tokenSecret: {{ .Values.main.tokenSecret }}
    tokenSecretNamespace: {{ .Values.main.tokenSecretNamespace }}
{{- end }} {{/* if and .Values.main.tokenSecret .Values.main.tokenSecretNamespace */}}
  multiSourceConfig:
    enabled: {{ .Values.main.multiSourceConfig.enabled }}
{{- if .Values.main.analyticsUUID }}
  analyticsUUID: {{ .Values.main.analyticsUUID }}
{{- end }} {{/* if .Values.main.analyticsUUID */}}
{{- if .Values.main.experimentalCapabilities }}
  experimentalCapabilities: {{ .Values.main.experimentalCapabilities }}
{{- end }} {{/* if .Values.main.experimentalCapabilities */}}
{{- if .Values.main.extraParameters }}
  extraParameters:
{{- range .Values.main.extraParameters }}
  - name: {{ .name | quote }}
    value: {{ .value | quote }}
{{- end }} {{/* range .Values.main.extraParameters */}}
{{- end }} {{/* if .Values.main.extraParameters */}}
{{- if .Values.global.extraValueFiles }}
  extraValueFiles:
{{- range .Values.global.extraValueFiles }}
  - {{ . | quote }}
{{- end }} {{/* range .Values.global.extraValueFiles */}}
{{- end }} {{/* if .Values.global.extraValueFiles */}}
