apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: patterns-operator
  namespace: openshift-operators
  labels:
    operators.coreos.com/patterns-operator.openshift-operators: ""
spec:
  channel: {{ .Values.main.patternsOperator.channel }}
  installPlanApproval: {{ .Values.main.patternsOperator.installPlanApproval }}
  name: patterns-operator
  source: {{ .Values.main.patternsOperator.source }}
  sourceNamespace: {{ .Values.main.patternsOperator.sourceNamespace }}
  {{- if .Values.main.patternsOperator.startingCSV }}
  startingCSV: {{ .Values.main.patternsOperator.startingCSV }}
  {{- end }}
