{{- if .Values.main.options.bootstrap }}
{{-   if eq .Values.global.imageregistry.type "openshift" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-edit
  namespace: openshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: manuela-ci
{{-   end }}
{{- end }}
