main:
  git:
    repoURL: https://github.com/example/common

secrets:
  # NEVER COMMIT THESE VALUES TO GIT
  imageregistry:
    # Quay -> Robot Accounts -> Robot Login
    account: test-account
    token:   test-quay-token

  git:
    # Go to: https://github.com/settings/tokens
    username: test-user
    token: test-git-token

  aws:
    s3Secret: test-secret

  # The cluster_xxxx pattern is used for creating externalSecrets that
  # will be used by ArgoCD to detect other clusters.
  #
  # Create a service account with enough permissions and extract the token
  #
  # CLUSTER_TOKEN=$(oc describe secret -n default argocd-external-token | grep 'token:' | awk '{print$2}')
  # CLUSTER_CA=$(oc extract -n openshift-config cm/kube-root-ca.crt --to=- --keys=ca.crt | base64 | awk '{print}' ORS='')
  cluster_example:
    name: example
    server: https://api.example.openshiftapps.com:6443
    config: |
      {
        \"bearerToken\": \"<bearer_token>\",
        \"tlsClientConfig\": {
          \"insecure\": false,
          \"caData\": \"<base64 encoded CA>\"
        }
      }