global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: example

  namespaces:
  - open-cluster-management
  - application-ci

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.4
      csv: advanced-cluster-management.v2.4.1

    odh:
      name: opendatahub-operator
      source: community-operators
      csv: opendatahub-operator.v1.1.0
      disabled: true

    pipelines:
      name: openshift-pipelines-operator-rh
      csv: redhat-openshift-pipelines.v1.5.2

  projects:
  - datacenter

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: datacenter
      path: common/acm
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
        - /spec/loggingCA
    pipe:
      name: pipelines
      namespace: application-ci
      project: datacenter
      path: charts/datacenter/pipelines

  managedClusterGroups:
  - name: acm-edge
    # Optional - Point to a different repo
    # repoURL: https://github.com/hybrid-cloud-patterns/mySite.git
    # Must contain values-{clustergroupname}.yaml at the top level
    targetRevision: main
    helmOverrides:
    # Values must be strings!
    - name: clusterGroup.isHubCluster
      value: "false"
    acmlabels:
    - name: clusterGroup
      value: acm-region
  - name: acm-provision-edge
    targetRevision: main
    helmOverrides:
    - name: clusterGroup.isHubCluster
      value: "false"
    clusterPools:
      exampleAWSPool:
        size: 3
        name: aws-ap
        openshiftVersion: 4.10.18
        baseDomain: blueprints.rhecoeng.com
        platform:
          aws:
            region: ap-southeast-2
        clusters:
        - One
      exampleAzurePool:
        name: azure-us
        openshiftVersion: 4.10.18
        baseDomain: blueprints.rhecoeng.com
        platform:
          azure:
            baseDomainResourceGroupName: dojo-dns-zones
            region: eastus
        clusters:
        - Two
        - Three
    acmlabels:
    - name: clusterGroup
      value: region
  - name: argo-edge
    hostedArgoSites:
    - name: perth
      domain: perth1.beekhof.net
      bearerKeyPath: secret/data/hub/cluster_perth
      caKeyPath: secret/data/hub/cluster_perth_ca
    - name: sydney
      domain: syd.beekhof.net
    helmOverrides:
    - name: clusterGroup.isHubCluster
      value: "false"
