{{- if not (eq .Values.clusterGroup.enabled "plumbing") }}
{{- $namespace := cat $.Values.global.pattern $.Values.clusterGroup.name | replace " " "-" }}
{{ if .Values.clusterGroup.isHubCluster }}
{{- range .Values.clusterGroup.managedClusterGroups }}
{{- $group := . }}
{{- range .argoClusterSeeds }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ . | kebabcase }}-secret
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "100"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ . | kebabcase }}-secret
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
      data:
        name: {{ . }}
        server: |-
          {{ "{{ .kubeServer | toString }}" }}
        config: |
          {
            "bearerToken": {{ "{{ .kubeBearer | toString | quote }}" }},
            "tlsClientConfig": {
              "insecure": false,
              "caData": {{ "{{ .kubeCA | toString | quote }}" }}
            }
          }
  data:
  - secretKey: kubeServer
    remoteRef:
      key: {{ $.Values.secretsBase.key }}/cluster_{{ . }}
      property: server
  - secretKey: kubeBearer
    remoteRef:
      key: {{ $.Values.secretsBase.key }}/cluster_{{ . }}
      property: bearerToken
  - secretKey: kubeCA
    remoteRef:
      key: {{ $.Values.secretsBase.key }}/cluster_{{ . }}_ca
      property: b64content
{{- end }}
{{- end }}
{{- end }}
{{- end }}
