---
- name: Run vault init tasks
  ansible.builtin.import_tasks: vault_init.yaml
  tags: vault_init

- name: Unseal vault
  ansible.builtin.import_tasks: vault_unseal.yaml
  tags: vault_unseal

- name: Vault secrets init
  ansible.builtin.import_tasks: vault_secrets_init.yaml
  tags: vault_secrets_init

- name: Vault spoke backend init
  ansible.builtin.import_tasks: vault_spokes_init.yaml
  tags: vault_spokes_init

- name: Load secrets
  ansible.builtin.import_tasks: push_secrets.yaml
  tags: push_secrets
