{{ if .Values.letsencrypt.enabled }}
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true, Validate=false, SkipDryRunOnMissingResource=true
spec:
  routeAdmission:
    wildcardPolicy: WildcardsAllowed
  defaultCertificate:
    name: lets-encrypt-wildcart-cert-tls
# Patch the cluster-wide argocd instance so it uses the ingress tls cert
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true, Validate=false, SkipDryRunOnMissingResource=true
spec:
  server:
    route:
      enabled: true
      tls:
         termination: reencrypt
{{ if .Values.letsencrypt.api_endpoint }}
---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true, Validate=false, SkipDryRunOnMissingResource=true
spec:
  servingCerts:
    namedCertificates:
      - names:
        - api.{{ $.Values.global.localClusterDomain | replace "apps." "" }}
        servingCertificate:
          name: api-validated-patterns-letsencrypt-cert
{{- end }}
{{- end }}
