{{- $backend := .Values.global.secretStore.backend | default "vault" }}
{{- if eq $backend "vault" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $backend }}-backend
  namespace: golang-external-secrets
spec:
  provider:
    vault:
      server: https://vault-vault.{{ .Values.global.hubClusterDomain }}
      path: secret
      # Version of KV backend
      version: v2
{{- if .Values.golangExternalSecrets.caProvider.enabled }}
{{ if .Values.clusterGroup.isHubCluster }}
      caProvider:
        type: {{ .Values.golangExternalSecrets.caProvider.hostCluster.type }}
        name: {{ .Values.golangExternalSecrets.caProvider.hostCluster.name }}
        key: {{ .Values.golangExternalSecrets.caProvider.hostCluster.key }}
        namespace: {{ .Values.golangExternalSecrets.caProvider.hostCluster.namespace }}
{{ else }}
      caProvider:
        type: {{ .Values.golangExternalSecrets.caProvider.clientCluster.type }}
        name: {{ .Values.golangExternalSecrets.caProvider.clientCluster.name }}
        key: {{ .Values.golangExternalSecrets.caProvider.clientCluster.key }}
        namespace: {{ .Values.golangExternalSecrets.caProvider.clientCluster.namespace }}
{{ end }}
{{- end }}
      auth:
        kubernetes:
{{ if .Values.clusterGroup.isHubCluster }}
          mountPath: {{ .Values.golangExternalSecrets.vault.mountPath }}
          role: {{ .Values.golangExternalSecrets.rbac.rolename }}
{{ else }}
          mountPath: {{ $.Values.global.clusterDomain }}
          role: {{ $.Values.global.clusterDomain }}-role
{{ end }}
          secretRef:
            name: golang-external-secrets
            namespace: golang-external-secrets
            key: "token"
{{- end }}
